spring.application.name=medicare

# Database Configuration (H2 In-Memory DB enabled for easy testing and local execution)
spring.datasource.url=jdbc:h2:mem:medicaredb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true

# MySQL configuration (Uncomment to use MySQL database)
# spring.datasource.url=jdbc:mysql://localhost:3306/medicare
# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# spring.datasource.username=root
# spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

